---
title: "Juvenile DA Analysis"
output: html_document
date: "2025-07-15"
---
\

Overview
------
**This repo demonstrates the entire data processing pipeline used to analyze longitudinal fiber photometry dopamine data synchronized with vocal behaviors in juvenile songbirds.**

We show how dopamine signals are aligned to behavioral events and analyzed to reveal how the development trajectory of dopamine transient activity corresponds to temporal-difference learning models.

All analyses and results are fully reproducible and correspond to those in our manuscript.
\
\

Installation
------
To reproduce the analyses, install the following R packages:
```{r, install_pkgs, eval = FALSE}
require(remotes)
# Install ASAP
remotes::install_github("LXiao06/ASAP")
# Or install local version
remotes::install_local("pkgs/ASAP_0.3.3.tar.gz", dependencies = TRUE)

# Install VNS
remotes::install_github("LXiao06/VocalNeuroSync")
# Or install local version
remotes::install_local("pkgs/VNS_0.0.0.9000.tar.gz", dependencies = TRUE)
```
For details, see the [ASAP GitHub repository](https://github.com/LXiao06/ASAP) and the [VocalNeuroSync repository](https://github.com/LXiao06/VocalNeuroSync).
\
\

Tutorials
------
<div style="font-size: 18px;">

- [Data Processing](data_processing.html)
- [Individual Analysis](individual_analysis.html)
- [Population Analysis](population_analysis.html)
\
\

### Data Availability

You may need to download the raw or processed data before running individual tutorials. See individual sections for details on required datasets.

>  **Raw data** used for [Data Processing](data_processing.html) is available at:
>
>  - [Duke University Library Research Data Repository (JuvDA directory)](https://doi.org/10.7924/r4s186852)
>  - Publication: [doi.org/10.1038/s41586-025-08694-9](https://doi.org/10.1038/s41586-025-08694-9)
>
>  **Processed data** used for [Individual Analysis](invidividual_analysis.html) and [Population Analysis](populaiton_analysis.html) is available at:
>
>  - [UT Southwestern Research Data Repository](link-to-processed-data-repo)
>  - Or generated from the raw data using the [Data Processing](data_processing.html) pipeline
>  - Publication: [doi.org/xxxx/xxx](link-to-manuscript)
