<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />



<meta name="date" content="2026-06-16" />

<title>Photometry Modeling: Shift-Only Time Warping of Pooled dLight Data</title>

<script src="site_libs/header-attrs-2.31/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Juvenile DA Analysis</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="diagram/interactive-flowchart.html">Analytics Architecture</a>
</li>
<li>
  <a href="data_processing.html">Data Processing</a>
</li>
<li>
  <a href="individual_analysis.html">Individual Analysis</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Population Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="population_analysis.html">Overview</a>
    </li>
    <li>
      <a href="weighted_LMMs.html">Weighted LMMs</a>
    </li>
    <li>
      <a href="balanced_resampling.html">Balanced Resampling</a>
    </li>
  </ul>
</li>
<li>
  <a href="photometry_modeling.html">Photometry Modeling</a>
</li>
<li>
  <a href="reference.html">Reference</a>
</li>
<li>
  <a href="https://github.com/LXiao06/Juvenile_DA_analysis">GitHub</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Photometry Modeling: Shift-Only Time
Warping of Pooled dLight Data</h1>
<h4 class="date">2026-06-16</h4>

</div>


<p><br />
</p>
<div id="overview" class="section level2">
<h2>Overview</h2>
<p><strong>This tutorial demonstrates the application of an unsupervised
shift-only time warping model to pooled dLight fiber photometry
recordings collected from juvenile songbirds at similar developmental
stages (early and late development), and compares them to full-adult
animals.</strong><br />
<br />
</p>
<p>The analysis addresses key limitations of standard supervised
alignment approaches and provides a more robust characterization of
dopamine temporal dynamics across a population of animals.</p>
<blockquote>
<h3 id="why-shift-only-time-warping">Why Shift-Only Time Warping?</h3>
<p><strong>Limitations of Supervised Approaches:</strong></p>
<ol style="list-style-type: decimal">
<li><strong>Alignment subjectivity:</strong> Manually selecting
alignment points (e.g., motif onset) can be subjective and inconsistent
across animals or renditions.</li>
<li><strong>Averaging bias:</strong> Trial-averaging after fixed
alignment can mask fine-grained temporal jitter in dLight activity,
obscuring true dynamics.</li>
</ol>
<p><strong>Advantages of the Shift-Only Model:</strong></p>
<ol style="list-style-type: decimal">
<li><strong>Unsupervised temporal discovery:</strong> The model
discovers precise temporal patterns without relying on pre-defined
behavioral events.</li>
<li><strong>Robustness to variability:</strong> By not anchoring to
behavioral events, the model naturally accommodates trial-to-trial
variability, enabling inclusion of both directed and undirected singing
data.</li>
</ol>
</blockquote>
<p><br />
</p>
</div>
<div id="citation" class="section level2">
<h2>Citation</h2>
<p>This analysis relies on the <code>affinewarp</code> package,
implementing piecewise linear time warping for multi-dimensional time
series:</p>
<blockquote>
<p>Williams AH, Poole B, Maheswaranathan N, Dhawale AK, Fisher T, Wilson
CD, Brann DH, Trautmann E, Ryu S, Shusterman R, Rinberg D, Ölveczky BP,
Shenoy KV, Ganguli S (2020). <strong>Discovering precise temporal
patterns in large-scale neural recordings through robust and
interpretable time warping.</strong> <em>Neuron</em>, 105(2):246-259.e8.
<a
href="https://doi.org/10.1016/j.neuron.2019.10.020">https://doi.org/10.1016/j.neuron.2019.10.020</a></p>
</blockquote>
<p>GitHub repository: <a
href="https://github.com/ahwillia/affinewarp">https://github.com/ahwillia/affinewarp</a></p>
<p><br />
</p>
</div>
<div id="install-required-packages" class="section level2">
<h2>Install Required Packages</h2>
<p>Install the <code>affinewarp</code> Python package before running
this analysis:</p>
<div class="sourceCode" id="cb1"><pre
class="sourceCode python"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co"># Install affinewarp from source</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="im">import</span> subprocess</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a>subprocess.run([<span class="st">&quot;pip&quot;</span>, <span class="st">&quot;install&quot;</span>, <span class="st">&quot;git+https://github.com/ahwillia/affinewarp.git&quot;</span>], check<span class="op">=</span><span class="va">True</span>)</span></code></pre></div>
<p>Alternatively, clone the repository and install locally:</p>
<div class="sourceCode" id="cb2"><pre
class="sourceCode bash"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="fu">git</span> clone https://github.com/ahwillia/affinewarp/</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="bu">cd</span> affinewarp</span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a><span class="ex">pip</span> install .</span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a><span class="ex">pip</span> install <span class="at">-r</span> requirements.txt</span></code></pre></div>
<p><br />
</p>
</div>
<div id="pooling-workflow" class="section level2">
<h2>Pooling Workflow</h2>
<p>This guide demonstrates how to generate and export population-level
multi-trial photometry data by extracting trials from individual
animals, balancing trial counts, and pooling them into unified arrays.
The workflow consists of four main steps:</p>
<div id="step-1-load-individual-npm-objects" class="section level3">
<h3>STEP 1: Load Individual NPM Objects</h3>
<p>Load the individual animal epoch-aligned fiber photometry object (an
R RDS file containing both neural and vocal event data):</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="fu">library</span>(VNS)</span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a>npm <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;./dev/rds/npm_B633_epoch.rds&quot;</span>)</span></code></pre></div>
<p><br />
</p>
</div>
<div id="step-2-extract-trial-aligned-photometry-data"
class="section level3">
<h3>STEP 2: Extract Trial-Aligned Photometry Data</h3>
<p>Extract trial segment matrices aligned to song motif onsets. In this
example, we extract the baseline-subtracted <code>processed</code>
photometry signals for specific developmental labels (ages
<code>72dph</code> and <code>91dph</code>):</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a>TOTAL_WINDOW <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>PRE_MOTIF_WINDOW <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" tabindex="-1"></a>B633_data <span class="ot">&lt;-</span> <span class="fu">extract_photometry_data</span>(npm,</span>
<span id="cb4-5"><a href="#cb4-5" tabindex="-1"></a>                                     <span class="at">data_type =</span> <span class="st">&quot;processed&quot;</span>,</span>
<span id="cb4-6"><a href="#cb4-6" tabindex="-1"></a>                                     <span class="at">region =</span> <span class="st">&quot;reg0&quot;</span>,</span>
<span id="cb4-7"><a href="#cb4-7" tabindex="-1"></a>                                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;72dph&quot;</span>, <span class="st">&quot;91dph&quot;</span>),</span>
<span id="cb4-8"><a href="#cb4-8" tabindex="-1"></a>                                     <span class="at">ref_line =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.4</span>, <span class="fl">0.4</span>),</span>
<span id="cb4-9"><a href="#cb4-9" tabindex="-1"></a>                                     <span class="at">total_window =</span> TOTAL_WINDOW,</span>
<span id="cb4-10"><a href="#cb4-10" tabindex="-1"></a>                                     <span class="at">pre_motif_window =</span> PRE_MOTIF_WINDOW)</span>
<span id="cb4-11"><a href="#cb4-11" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" tabindex="-1"></a>B633_early <span class="ot">&lt;-</span> B633_data[[<span class="st">&quot;72dph&quot;</span>]]</span>
<span id="cb4-13"><a href="#cb4-13" tabindex="-1"></a>B633_late <span class="ot">&lt;-</span> B633_data[[<span class="st">&quot;91dph&quot;</span>]]</span></code></pre></div>
<p><br />
</p>
</div>
<div id="step-3-iterate-across-all-animals" class="section level3">
<h3>STEP 3: Iterate Across All Animals</h3>
<p>Repeat the data loading and extraction pipeline (Steps 1 &amp; 2) for
all other individual animals in your study to generate their respective
trial-aligned matrices (e.g., <code>P569_early</code>,
<code>R561_early</code>, <code>P568_early</code>,
<code>R562_late</code>, <code>P569_late</code>, etc.).</p>
<p><br />
</p>
</div>
<div id="step-4-pool-matrices-with-trial-balancing"
class="section level3">
<h3>STEP 4: Pool Matrices with Trial Balancing</h3>
<p>Pool individual bird matrices together into a population array for
each developmental stage. Setting <code>balance = TRUE</code>
downsamples trials so that all subjects contribute an equal number of
trials, preventing any single bird from bias-dominating the pool:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="co"># Pool early development matrices</span></span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>early_pool <span class="ot">&lt;-</span> <span class="fu">pool_photometry_data</span>(<span class="fu">list</span>(</span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a>  <span class="at">B633 =</span> B633_early,</span>
<span id="cb5-4"><a href="#cb5-4" tabindex="-1"></a>  <span class="at">P569 =</span> P569_early,</span>
<span id="cb5-5"><a href="#cb5-5" tabindex="-1"></a>  <span class="at">R561 =</span> R561_early,</span>
<span id="cb5-6"><a href="#cb5-6" tabindex="-1"></a>  <span class="at">P568 =</span> P568_early),</span>
<span id="cb5-7"><a href="#cb5-7" tabindex="-1"></a>  <span class="at">balance =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-8"><a href="#cb5-8" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" tabindex="-1"></a><span class="co"># Pool late development matrices</span></span>
<span id="cb5-10"><a href="#cb5-10" tabindex="-1"></a>late_pool <span class="ot">&lt;-</span> <span class="fu">pool_photometry_data</span>(<span class="fu">list</span>(</span>
<span id="cb5-11"><a href="#cb5-11" tabindex="-1"></a>  <span class="at">B633 =</span> B633_late,</span>
<span id="cb5-12"><a href="#cb5-12" tabindex="-1"></a>  <span class="at">R562 =</span> R562_late,</span>
<span id="cb5-13"><a href="#cb5-13" tabindex="-1"></a>  <span class="at">P569 =</span> P569_late),</span>
<span id="cb5-14"><a href="#cb5-14" tabindex="-1"></a>  <span class="at">balance =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><br />
</p>
</div>
<div id="step-5-export-to-python-compatible-numpy-format"
class="section level3">
<h3>STEP 5: Export to Python-Compatible NumPy Format</h3>
<p>Save the pooled population matrices as NumPy <code>.npy</code> files.
These files will be stored in the <code>./data</code> folder, allowing
them to be loaded directly in Python:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="fu">save_npy</span>(early_pool,</span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>         <span class="at">output_dir =</span> <span class="st">&quot;data&quot;</span>,</span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>         <span class="at">python_path =</span> <span class="st">&quot;/usr/bin/python3&quot;</span>,</span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>         <span class="at">file_prefix =</span> <span class="st">&quot;early_dev_pool&quot;</span>)</span>
<span id="cb6-5"><a href="#cb6-5" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" tabindex="-1"></a><span class="fu">save_npy</span>(late_pool,</span>
<span id="cb6-7"><a href="#cb6-7" tabindex="-1"></a>         <span class="at">output_dir =</span> <span class="st">&quot;data&quot;</span>,</span>
<span id="cb6-8"><a href="#cb6-8" tabindex="-1"></a>         <span class="at">python_path =</span> <span class="st">&quot;/usr/bin/python3&quot;</span>,</span>
<span id="cb6-9"><a href="#cb6-9" tabindex="-1"></a>         <span class="at">file_prefix =</span> <span class="st">&quot;late_dev_pool&quot;</span>)</span></code></pre></div>
<p>Once exported, these <code>.npy</code> files can be loaded directly
into your Python workspace using <code>np.load()</code> for downstream
shift-only warping analysis.</p>
<p><br />
</p>
</div>
</div>
<div id="setup" class="section level2">
<h2>Setup</h2>
<div class="sourceCode" id="cb7"><pre
class="sourceCode python"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a><span class="im">from</span> affinewarp <span class="im">import</span> ShiftWarping</span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb7-4"><a href="#cb7-4" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb7-5"><a href="#cb7-5" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" tabindex="-1"></a><span class="co"># %matplotlib inline</span></span>
<span id="cb7-7"><a href="#cb7-7" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" tabindex="-1"></a><span class="co"># Figure output directory</span></span>
<span id="cb7-9"><a href="#cb7-9" tabindex="-1"></a>FIGURE_DIR <span class="op">=</span> <span class="st">&quot;./figs&quot;</span></span>
<span id="cb7-10"><a href="#cb7-10" tabindex="-1"></a>os.makedirs(FIGURE_DIR, exist_ok<span class="op">=</span><span class="va">True</span>)</span></code></pre></div>
<p><br />
</p>
</div>
<div id="load-pooled-dlight-data" class="section level2">
<h2>Load Pooled dLight Data</h2>
<p>Load the pooled dLight recordings for three groups. The data arrays
are shaped <code>(trials, time_bins, 1)</code>:</p>
<table>
<colgroup>
<col width="25%" />
<col width="25%" />
<col width="25%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th>Dataset</th>
<th>File</th>
<th>Window</th>
<th>Sampling</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Early development</strong></td>
<td><code>early_dev_pool_2s.npy</code></td>
<td>2 s</td>
<td>~66.7 ms/bin (30 bins)</td>
</tr>
<tr class="even">
<td><strong>Late development</strong></td>
<td><code>late_dev_pool_2s.npy</code></td>
<td>2 s</td>
<td>~66.7 ms/bin (30 bins)</td>
</tr>
<tr class="odd">
<td><strong>Full adult</strong></td>
<td><code>adult_pool_2s.npy</code></td>
<td>2 s</td>
<td>~48.8 ms/bin (41 bins)</td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Note:</strong> The juvenile and adult datasets were recorded
at different sampling rates, so each group’s time axis must be
constructed from its own bin count and window duration.</p>
</blockquote>
<div class="sourceCode" id="cb8"><pre
class="sourceCode python"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="co"># Juvenile recording parameters</span></span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>JUV_TOTAL_WINDOW <span class="op">=</span> <span class="fl">2.0</span>   <span class="co"># total window (seconds)</span></span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a>JUV_MOTIF_ONSET  <span class="op">=</span> <span class="fl">0.5</span>   <span class="co"># pre-motif baseline (seconds)</span></span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" tabindex="-1"></a><span class="co"># Adult recording parameters</span></span>
<span id="cb8-6"><a href="#cb8-6" tabindex="-1"></a>ADULT_TOTAL_WINDOW <span class="op">=</span> <span class="fl">2.0</span></span>
<span id="cb8-7"><a href="#cb8-7" tabindex="-1"></a>ADULT_MOTIF_ONSET  <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb8-8"><a href="#cb8-8" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" tabindex="-1"></a>DATA_DIR <span class="op">=</span> <span class="st">&quot;./data&quot;</span></span>
<span id="cb8-10"><a href="#cb8-10" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" tabindex="-1"></a><span class="co"># Early development — pooled across animals</span></span>
<span id="cb8-12"><a href="#cb8-12" tabindex="-1"></a>early_dev <span class="op">=</span> np.load(os.path.join(DATA_DIR, <span class="st">&quot;early_dev_pool_2s.npy&quot;</span>))  <span class="co"># (trials, bins, 1)</span></span>
<span id="cb8-13"><a href="#cb8-13" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" tabindex="-1"></a><span class="co"># Late development — pooled across animals</span></span>
<span id="cb8-15"><a href="#cb8-15" tabindex="-1"></a>late_dev <span class="op">=</span> np.load(os.path.join(DATA_DIR, <span class="st">&quot;late_dev_pool_2s.npy&quot;</span>))    <span class="co"># (trials, bins, 1)</span></span>
<span id="cb8-16"><a href="#cb8-16" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" tabindex="-1"></a><span class="co"># Full adult</span></span>
<span id="cb8-18"><a href="#cb8-18" tabindex="-1"></a>raw_adult <span class="op">=</span> np.load(os.path.join(DATA_DIR, <span class="st">&quot;adult_pool_2s.npy&quot;</span>))      <span class="co"># (trials, bins) or (trials, bins, 1)</span></span>
<span id="cb8-19"><a href="#cb8-19" tabindex="-1"></a><span class="cf">if</span> raw_adult.ndim <span class="op">==</span> <span class="dv">2</span>:</span>
<span id="cb8-20"><a href="#cb8-20" tabindex="-1"></a>    raw_adult <span class="op">=</span> raw_adult[:, :, np.newaxis]                            <span class="co"># -&gt; (trials, bins, 1)</span></span>
<span id="cb8-21"><a href="#cb8-21" tabindex="-1"></a></span>
<span id="cb8-22"><a href="#cb8-22" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;early_dev : </span><span class="sc">{</span>early_dev<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">  | &quot;</span></span>
<span id="cb8-23"><a href="#cb8-23" tabindex="-1"></a>      <span class="ss">f&quot;</span><span class="sc">{</span>JUV_TOTAL_WINDOW <span class="op">*</span> <span class="dv">1000</span> <span class="op">/</span> early_dev<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">:.1f}</span><span class="ss"> ms/bin&quot;</span>)</span>
<span id="cb8-24"><a href="#cb8-24" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;late_dev  : </span><span class="sc">{</span>late_dev<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">   | &quot;</span></span>
<span id="cb8-25"><a href="#cb8-25" tabindex="-1"></a>      <span class="ss">f&quot;</span><span class="sc">{</span>JUV_TOTAL_WINDOW <span class="op">*</span> <span class="dv">1000</span> <span class="op">/</span> late_dev<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">:.1f}</span><span class="ss"> ms/bin&quot;</span>)</span>
<span id="cb8-26"><a href="#cb8-26" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;raw_adult : </span><span class="sc">{</span>raw_adult<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">  | &quot;</span></span>
<span id="cb8-27"><a href="#cb8-27" tabindex="-1"></a>      <span class="ss">f&quot;</span><span class="sc">{</span>ADULT_TOTAL_WINDOW <span class="op">*</span> <span class="dv">1000</span> <span class="op">/</span> raw_adult<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">:.1f}</span><span class="ss"> ms/bin&quot;</span>)</span></code></pre></div>
<pre><code>## early_dev : (266, 30, 1)  | 66.7 ms/bin
## late_dev  : (132, 30, 1)  | 66.7 ms/bin
## raw_adult : (156, 41, 1)  | 48.8 ms/bin</code></pre>
<p><br />
</p>
</div>
<div id="fit-shift-only-warping-models" class="section level2">
<h2>Fit Shift-Only Warping Models</h2>
<p>A <strong>ShiftWarping</strong> model is fit independently to each
group using the same hyperparameters:</p>
<ul>
<li><code>maxlag = 0.2</code> — maximum allowed shift is ±20% of the
window duration</li>
<li><code>smoothness_reg_scale = 10.0</code> — regularization on
template smoothness</li>
<li><code>iterations = 20</code> — number of alternating optimization
steps</li>
</ul>
<div class="sourceCode" id="cb10"><pre
class="sourceCode python"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="co"># Shared hyperparameters</span></span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>MAXLAG           <span class="op">=</span> <span class="fl">0.2</span></span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>SMOOTHNESS_SCALE <span class="op">=</span> <span class="fl">10.0</span></span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a>FIT_ITERATIONS   <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb10-5"><a href="#cb10-5" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" tabindex="-1"></a>early_dev_model <span class="op">=</span> ShiftWarping(maxlag<span class="op">=</span>MAXLAG, smoothness_reg_scale<span class="op">=</span>SMOOTHNESS_SCALE)</span>
<span id="cb10-7"><a href="#cb10-7" tabindex="-1"></a>early_dev_model.fit(early_dev, iterations<span class="op">=</span>FIT_ITERATIONS)</span>
<span id="cb10-8"><a href="#cb10-8" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" tabindex="-1"></a>late_dev_model <span class="op">=</span> ShiftWarping(maxlag<span class="op">=</span>MAXLAG, smoothness_reg_scale<span class="op">=</span>SMOOTHNESS_SCALE)</span>
<span id="cb10-10"><a href="#cb10-10" tabindex="-1"></a>late_dev_model.fit(late_dev, iterations<span class="op">=</span>FIT_ITERATIONS)</span>
<span id="cb10-11"><a href="#cb10-11" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" tabindex="-1"></a>adult_model <span class="op">=</span> ShiftWarping(maxlag<span class="op">=</span>MAXLAG, smoothness_reg_scale<span class="op">=</span>SMOOTHNESS_SCALE)</span>
<span id="cb10-13"><a href="#cb10-13" tabindex="-1"></a>adult_model.fit(raw_adult, iterations<span class="op">=</span>FIT_ITERATIONS)</span></code></pre></div>
<p><br />
</p>
<div id="learning-curves" class="section level3">
<h3>Learning Curves</h3>
<p>The loss (reconstruction error) should decrease monotonically over
iterations. Convergence before 20 steps indicates the model has found a
stable solution.</p>
<div class="sourceCode" id="cb11"><pre
class="sourceCode python"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="co"># Plot one learning-curve panel per model (matching the notebook&#39;s subplot layout)</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>model_list  <span class="op">=</span> [early_dev_model, late_dev_model, adult_model]</span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>model_names <span class="op">=</span> [<span class="st">&quot;Early Dev&quot;</span>, <span class="st">&quot;Late Dev&quot;</span>, <span class="st">&quot;Adult&quot;</span>]</span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">4</span>))</span>
<span id="cb11-6"><a href="#cb11-6" tabindex="-1"></a><span class="cf">for</span> ax, model, name <span class="kw">in</span> <span class="bu">zip</span>(axes, model_list, model_names):</span>
<span id="cb11-7"><a href="#cb11-7" tabindex="-1"></a>    ax.plot(model.loss_hist)</span>
<span id="cb11-8"><a href="#cb11-8" tabindex="-1"></a>    ax.set_xlabel(<span class="st">&quot;Iterations&quot;</span>)</span>
<span id="cb11-9"><a href="#cb11-9" tabindex="-1"></a>    ax.set_ylabel(<span class="st">&quot;Model loss&quot;</span>)</span>
<span id="cb11-10"><a href="#cb11-10" tabindex="-1"></a>    ax.set_title(<span class="ss">f&quot;</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> Model Learning Curve&quot;</span>)</span>
<span id="cb11-11"><a href="#cb11-11" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb11-13"><a href="#cb11-13" tabindex="-1"></a>fig_path <span class="op">=</span> os.path.join(FIGURE_DIR, <span class="st">&quot;photometry_modeling_learning_curves.png&quot;</span>)</span>
<span id="cb11-14"><a href="#cb11-14" tabindex="-1"></a>fig.savefig(fig_path, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">&quot;tight&quot;</span>)</span>
<span id="cb11-15"><a href="#cb11-15" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Saved: </span><span class="sc">{</span>fig_path<span class="sc">}</span><span class="ss">&quot;</span>)</span>
<span id="cb11-16"><a href="#cb11-16" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img
src="figs/photometry_modeling_learning_curves.png" /><!-- --></p>
<p><br />
</p>
</div>
</div>
<div
id="main-visualization-raw-model-estimate-aligned-trial-average-and-template"
class="section level2">
<h2>Main Visualization: Raw, Model Estimate, Aligned, Trial Average, and
Template</h2>
<p>The figure below presents, for each group (Early Development, Late
Development, Full Adult), five rows:</p>
<ol style="list-style-type: decimal">
<li><strong>Raw dLight</strong> — unaligned fluorescence heatmap (trials
× absolute time)</li>
<li><strong>Model estimate</strong> — the model’s reconstruction via
<code>model.predict()</code></li>
<li><strong>Shift-aligned raw</strong> — raw traces reindexed by learned
shifts</li>
<li><strong>Trial average</strong> — naive mean (black)
vs. shift-aligned mean (red), with 95% CI ribbons</li>
<li><strong>Model template</strong> — the consensus temporal profile
(blue)</li>
</ol>
<blockquote>
<p><strong>Note:</strong> The adult data (Column 3) has 41 time bins
over 2 s (~48.8 ms/bin), whereas the juvenile data have 30 bins over 2 s
(~66.7 ms/bin). Time axes are absolute (0 to window duration); a dashed
vertical line marks motif onset.</p>
</blockquote>
<div class="sourceCode" id="cb12"><pre
class="sourceCode python"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="kw">def</span> get_clock_time(data, time_window):</span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>    <span class="co">&quot;&quot;&quot;Return absolute time array from 0 to time_window (seconds).&quot;&quot;&quot;</span></span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>    <span class="cf">return</span> np.linspace(<span class="dv">0</span>, time_window, data.shape[<span class="dv">1</span>])</span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" tabindex="-1"></a><span class="kw">def</span> plot_heatmap_col(ax, data, vmin, vmax, total_window, title<span class="op">=</span><span class="va">None</span>, ylabel<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb12-7"><a href="#cb12-7" tabindex="-1"></a>    <span class="co">&quot;&quot;&quot;Plot a trials x time heatmap with inferno colormap.&quot;&quot;&quot;</span></span>
<span id="cb12-8"><a href="#cb12-8" tabindex="-1"></a>    hmap_kws <span class="op">=</span> <span class="bu">dict</span>(aspect<span class="op">=</span><span class="st">&quot;auto&quot;</span>, cmap<span class="op">=</span><span class="st">&quot;inferno&quot;</span>,</span>
<span id="cb12-9"><a href="#cb12-9" tabindex="-1"></a>                    extent<span class="op">=</span>[<span class="dv">0</span>, total_window, data.shape[<span class="dv">0</span>], <span class="dv">0</span>])</span>
<span id="cb12-10"><a href="#cb12-10" tabindex="-1"></a>    im <span class="op">=</span> ax.imshow(np.squeeze(data), vmin<span class="op">=</span>vmin, vmax<span class="op">=</span>vmax, <span class="op">**</span>hmap_kws)</span>
<span id="cb12-11"><a href="#cb12-11" tabindex="-1"></a>    ax.set_xlabel(<span class="st">&quot;time (s)&quot;</span>)</span>
<span id="cb12-12"><a href="#cb12-12" tabindex="-1"></a>    ax.set_ylabel(ylabel <span class="kw">or</span> <span class="st">&quot;renditions&quot;</span>)</span>
<span id="cb12-13"><a href="#cb12-13" tabindex="-1"></a>    <span class="cf">if</span> title:</span>
<span id="cb12-14"><a href="#cb12-14" tabindex="-1"></a>        ax.set_title(title)</span>
<span id="cb12-15"><a href="#cb12-15" tabindex="-1"></a>    <span class="cf">return</span> im</span>
<span id="cb12-16"><a href="#cb12-16" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" tabindex="-1"></a><span class="kw">def</span> plot_model_estimate_col(ax, model, total_window, n_trials):</span>
<span id="cb12-19"><a href="#cb12-19" tabindex="-1"></a>    <span class="co">&quot;&quot;&quot;Plot model reconstruction (model.predict()) with fixed vmin/vmax.&quot;&quot;&quot;</span></span>
<span id="cb12-20"><a href="#cb12-20" tabindex="-1"></a>    hmap_kws <span class="op">=</span> <span class="bu">dict</span>(aspect<span class="op">=</span><span class="st">&quot;auto&quot;</span>, cmap<span class="op">=</span><span class="st">&quot;inferno&quot;</span>,</span>
<span id="cb12-21"><a href="#cb12-21" tabindex="-1"></a>                    extent<span class="op">=</span>[<span class="dv">0</span>, total_window, n_trials, <span class="dv">0</span>])</span>
<span id="cb12-22"><a href="#cb12-22" tabindex="-1"></a>    im <span class="op">=</span> ax.imshow(model.predict().squeeze(),</span>
<span id="cb12-23"><a href="#cb12-23" tabindex="-1"></a>                   norm<span class="op">=</span>plt.Normalize(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>), <span class="op">**</span>hmap_kws)</span>
<span id="cb12-24"><a href="#cb12-24" tabindex="-1"></a>    ax.set_xlabel(<span class="st">&quot;time (s)&quot;</span>)</span>
<span id="cb12-25"><a href="#cb12-25" tabindex="-1"></a>    ax.set_ylabel(<span class="st">&quot;renditions&quot;</span>)</span>
<span id="cb12-26"><a href="#cb12-26" tabindex="-1"></a>    <span class="cf">return</span> im</span>
<span id="cb12-27"><a href="#cb12-27" tabindex="-1"></a></span>
<span id="cb12-28"><a href="#cb12-28" tabindex="-1"></a></span>
<span id="cb12-29"><a href="#cb12-29" tabindex="-1"></a><span class="kw">def</span> plot_trial_average_col(ax, data, model, total_window, motif_onset,</span>
<span id="cb12-30"><a href="#cb12-30" tabindex="-1"></a>                           color<span class="op">=</span><span class="st">&quot;r&quot;</span>, ylim<span class="op">=</span>(<span class="op">-</span><span class="fl">0.8</span>, <span class="fl">1.5</span>)):</span>
<span id="cb12-31"><a href="#cb12-31" tabindex="-1"></a>    <span class="co">&quot;&quot;&quot;Warped mean (colored) + naive mean (black) with 95 % CI ribbons.&quot;&quot;&quot;</span></span>
<span id="cb12-32"><a href="#cb12-32" tabindex="-1"></a>    clock <span class="op">=</span> get_clock_time(data, total_window)</span>
<span id="cb12-33"><a href="#cb12-33" tabindex="-1"></a></span>
<span id="cb12-34"><a href="#cb12-34" tabindex="-1"></a>    warped     <span class="op">=</span> model.transform(data)[:, :, <span class="dv">0</span>]</span>
<span id="cb12-35"><a href="#cb12-35" tabindex="-1"></a>    mean_w     <span class="op">=</span> warped.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb12-36"><a href="#cb12-36" tabindex="-1"></a>    ci_w       <span class="op">=</span> <span class="fl">1.96</span> <span class="op">*</span> warped.std(axis<span class="op">=</span><span class="dv">0</span>) <span class="op">/</span> np.sqrt(data.shape[<span class="dv">0</span>])</span>
<span id="cb12-37"><a href="#cb12-37" tabindex="-1"></a></span>
<span id="cb12-38"><a href="#cb12-38" tabindex="-1"></a>    naive      <span class="op">=</span> data[:, :, <span class="dv">0</span>]</span>
<span id="cb12-39"><a href="#cb12-39" tabindex="-1"></a>    mean_n     <span class="op">=</span> naive.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb12-40"><a href="#cb12-40" tabindex="-1"></a>    ci_n       <span class="op">=</span> <span class="fl">1.96</span> <span class="op">*</span> naive.std(axis<span class="op">=</span><span class="dv">0</span>)  <span class="op">/</span> np.sqrt(data.shape[<span class="dv">0</span>])</span>
<span id="cb12-41"><a href="#cb12-41" tabindex="-1"></a></span>
<span id="cb12-42"><a href="#cb12-42" tabindex="-1"></a>    ax.plot(clock, mean_w, color<span class="op">=</span>color, label<span class="op">=</span><span class="st">&quot;Warped Mean&quot;</span>)</span>
<span id="cb12-43"><a href="#cb12-43" tabindex="-1"></a>    ax.fill_between(clock, mean_w <span class="op">-</span> ci_w, mean_w <span class="op">+</span> ci_w, color<span class="op">=</span>color, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb12-44"><a href="#cb12-44" tabindex="-1"></a>    ax.plot(clock, mean_n, color<span class="op">=</span><span class="st">&quot;k&quot;</span>, label<span class="op">=</span><span class="st">&quot;Naive Mean&quot;</span>)</span>
<span id="cb12-45"><a href="#cb12-45" tabindex="-1"></a>    ax.fill_between(clock, mean_n <span class="op">-</span> ci_n, mean_n <span class="op">+</span> ci_n, color<span class="op">=</span><span class="st">&quot;k&quot;</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb12-46"><a href="#cb12-46" tabindex="-1"></a>    ax.axvline(x<span class="op">=</span>motif_onset, color<span class="op">=</span><span class="st">&quot;k&quot;</span>, linestyle<span class="op">=</span><span class="st">&quot;--&quot;</span>)</span>
<span id="cb12-47"><a href="#cb12-47" tabindex="-1"></a>    ax.set_xlabel(<span class="st">&quot;Time (s)&quot;</span>)</span>
<span id="cb12-48"><a href="#cb12-48" tabindex="-1"></a>    ax.set_ylabel(<span class="st">&quot;Trial-averaged dLight Activity&quot;</span>)</span>
<span id="cb12-49"><a href="#cb12-49" tabindex="-1"></a>    ax.set_ylim(ylim)</span>
<span id="cb12-50"><a href="#cb12-50" tabindex="-1"></a>    ax.legend()</span>
<span id="cb12-51"><a href="#cb12-51" tabindex="-1"></a></span>
<span id="cb12-52"><a href="#cb12-52" tabindex="-1"></a></span>
<span id="cb12-53"><a href="#cb12-53" tabindex="-1"></a><span class="kw">def</span> plot_template_col(ax, data, model, total_window, motif_onset,</span>
<span id="cb12-54"><a href="#cb12-54" tabindex="-1"></a>                      ylim<span class="op">=</span>(<span class="op">-</span><span class="fl">0.6</span>, <span class="fl">1.0</span>)):</span>
<span id="cb12-55"><a href="#cb12-55" tabindex="-1"></a>    <span class="co">&quot;&quot;&quot;Model template in blue; motif onset dashed line.&quot;&quot;&quot;</span></span>
<span id="cb12-56"><a href="#cb12-56" tabindex="-1"></a>    clock <span class="op">=</span> get_clock_time(data, total_window)</span>
<span id="cb12-57"><a href="#cb12-57" tabindex="-1"></a>    ax.plot(clock, model.template, <span class="st">&quot;-&quot;</span>, color<span class="op">=</span><span class="st">&quot;b&quot;</span>,</span>
<span id="cb12-58"><a href="#cb12-58" tabindex="-1"></a>            label<span class="op">=</span><span class="st">&quot;Model Template&quot;</span>, lw<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb12-59"><a href="#cb12-59" tabindex="-1"></a>    ax.set_xlabel(<span class="st">&quot;Time (s)&quot;</span>)</span>
<span id="cb12-60"><a href="#cb12-60" tabindex="-1"></a>    ax.set_ylabel(<span class="st">&quot;DA Activity&quot;</span>)</span>
<span id="cb12-61"><a href="#cb12-61" tabindex="-1"></a>    ax.set_ylim(ylim)</span>
<span id="cb12-62"><a href="#cb12-62" tabindex="-1"></a>    ax.legend()</span>
<span id="cb12-63"><a href="#cb12-63" tabindex="-1"></a>    ax.axvline(x<span class="op">=</span>motif_onset, color<span class="op">=</span><span class="st">&quot;k&quot;</span>, linestyle<span class="op">=</span><span class="st">&quot;--&quot;</span>)</span>
<span id="cb12-64"><a href="#cb12-64" tabindex="-1"></a>    ax.text(motif_onset <span class="op">+</span> <span class="fl">0.05</span>, ylim[<span class="dv">0</span>], <span class="st">&quot;Motif Onset&quot;</span>,</span>
<span id="cb12-65"><a href="#cb12-65" tabindex="-1"></a>            color<span class="op">=</span><span class="st">&quot;k&quot;</span>, ha<span class="op">=</span><span class="st">&quot;left&quot;</span>, va<span class="op">=</span><span class="st">&quot;bottom&quot;</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span></code></pre></div>
<div class="sourceCode" id="cb13"><pre
class="sourceCode python"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="co"># Shared colour scale across all three datasets</span></span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>vmin <span class="op">=</span> <span class="bu">min</span>(early_dev.<span class="bu">min</span>(), late_dev.<span class="bu">min</span>(), raw_adult.<span class="bu">min</span>())</span>
<span id="cb13-3"><a href="#cb13-3" tabindex="-1"></a>vmax <span class="op">=</span> <span class="bu">max</span>(early_dev.<span class="bu">max</span>(), late_dev.<span class="bu">max</span>(), raw_adult.<span class="bu">max</span>())</span>
<span id="cb13-4"><a href="#cb13-4" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" tabindex="-1"></a>col_titles <span class="op">=</span> [<span class="st">&quot;Early Development&quot;</span>, <span class="st">&quot;Late Development&quot;</span>, <span class="st">&quot;Full Adult&quot;</span>]</span>
<span id="cb13-6"><a href="#cb13-6" tabindex="-1"></a>row_titles <span class="op">=</span> [<span class="st">&quot;Raw&quot;</span>, <span class="st">&quot;Denoised&quot;</span>, <span class="st">&quot;Raw Aligned by Model&quot;</span>]</span>
<span id="cb13-7"><a href="#cb13-7" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" tabindex="-1"></a>datasets <span class="op">=</span> [</span>
<span id="cb13-9"><a href="#cb13-9" tabindex="-1"></a>    (early_dev, early_dev_model, JUV_TOTAL_WINDOW,   JUV_MOTIF_ONSET,   <span class="st">&quot;r&quot;</span>),</span>
<span id="cb13-10"><a href="#cb13-10" tabindex="-1"></a>    (late_dev,  late_dev_model,  JUV_TOTAL_WINDOW,   JUV_MOTIF_ONSET,   <span class="st">&quot;r&quot;</span>),</span>
<span id="cb13-11"><a href="#cb13-11" tabindex="-1"></a>    (raw_adult, adult_model,     ADULT_TOTAL_WINDOW, ADULT_MOTIF_ONSET, <span class="st">&quot;r&quot;</span>),</span>
<span id="cb13-12"><a href="#cb13-12" tabindex="-1"></a>]</span>
<span id="cb13-13"><a href="#cb13-13" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" tabindex="-1"></a>plt.rcParams.update({<span class="st">&quot;font.size&quot;</span>: <span class="dv">14</span>})</span>
<span id="cb13-15"><a href="#cb13-15" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">5</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">18</span>, <span class="dv">20</span>))</span>
<span id="cb13-16"><a href="#cb13-16" tabindex="-1"></a></span>
<span id="cb13-17"><a href="#cb13-17" tabindex="-1"></a><span class="cf">for</span> col, (data, model, tw, mo, col_color) <span class="kw">in</span> <span class="bu">enumerate</span>(datasets):</span>
<span id="cb13-18"><a href="#cb13-18" tabindex="-1"></a></span>
<span id="cb13-19"><a href="#cb13-19" tabindex="-1"></a>    <span class="co"># Row 0: Raw heatmap</span></span>
<span id="cb13-20"><a href="#cb13-20" tabindex="-1"></a>    im_raw <span class="op">=</span> plot_heatmap_col(axes[<span class="dv">0</span>, col], data, vmin, vmax, tw,</span>
<span id="cb13-21"><a href="#cb13-21" tabindex="-1"></a>                              title<span class="op">=</span>col_titles[col])</span>
<span id="cb13-22"><a href="#cb13-22" tabindex="-1"></a></span>
<span id="cb13-23"><a href="#cb13-23" tabindex="-1"></a>    <span class="co"># Row 1: Model estimate  (model.predict() with its own normalisation)</span></span>
<span id="cb13-24"><a href="#cb13-24" tabindex="-1"></a>    im_est <span class="op">=</span> plot_model_estimate_col(axes[<span class="dv">1</span>, col], model, tw, data.shape[<span class="dv">0</span>])</span>
<span id="cb13-25"><a href="#cb13-25" tabindex="-1"></a></span>
<span id="cb13-26"><a href="#cb13-26" tabindex="-1"></a>    <span class="co"># Row 2: Shift-aligned raw</span></span>
<span id="cb13-27"><a href="#cb13-27" tabindex="-1"></a>    im_alg <span class="op">=</span> plot_heatmap_col(axes[<span class="dv">2</span>, col], model.transform(data), vmin, vmax, tw)</span>
<span id="cb13-28"><a href="#cb13-28" tabindex="-1"></a></span>
<span id="cb13-29"><a href="#cb13-29" tabindex="-1"></a>    <span class="co"># Row 3: Trial averages with CI</span></span>
<span id="cb13-30"><a href="#cb13-30" tabindex="-1"></a>    plot_trial_average_col(axes[<span class="dv">3</span>, col], data, model, tw, mo,</span>
<span id="cb13-31"><a href="#cb13-31" tabindex="-1"></a>                           color<span class="op">=</span>col_color)</span>
<span id="cb13-32"><a href="#cb13-32" tabindex="-1"></a></span>
<span id="cb13-33"><a href="#cb13-33" tabindex="-1"></a>    <span class="co"># Row 4: Model template</span></span>
<span id="cb13-34"><a href="#cb13-34" tabindex="-1"></a>    plot_template_col(axes[<span class="dv">4</span>, col], data, model, tw, mo)</span>
<span id="cb13-35"><a href="#cb13-35" tabindex="-1"></a></span>
<span id="cb13-36"><a href="#cb13-36" tabindex="-1"></a><span class="co"># Add colorbars to the right of column 2 (Full Adult) without shrinking column 2</span></span>
<span id="cb13-37"><a href="#cb13-37" tabindex="-1"></a>pos0 <span class="op">=</span> axes[<span class="dv">0</span>, <span class="dv">2</span>].get_position()</span>
<span id="cb13-38"><a href="#cb13-38" tabindex="-1"></a>cax0 <span class="op">=</span> fig.add_axes([pos0.x1 <span class="op">+</span> <span class="fl">0.015</span>, pos0.y0, <span class="fl">0.012</span>, pos0.height])</span>
<span id="cb13-39"><a href="#cb13-39" tabindex="-1"></a>fig.colorbar(im_raw, cax<span class="op">=</span>cax0, label<span class="op">=</span><span class="st">&quot;dlight df/f&quot;</span>)</span>
<span id="cb13-40"><a href="#cb13-40" tabindex="-1"></a></span>
<span id="cb13-41"><a href="#cb13-41" tabindex="-1"></a>pos1 <span class="op">=</span> axes[<span class="dv">1</span>, <span class="dv">2</span>].get_position()</span>
<span id="cb13-42"><a href="#cb13-42" tabindex="-1"></a>cax1 <span class="op">=</span> fig.add_axes([pos1.x1 <span class="op">+</span> <span class="fl">0.015</span>, pos1.y0, <span class="fl">0.012</span>, pos1.height])</span>
<span id="cb13-43"><a href="#cb13-43" tabindex="-1"></a>fig.colorbar(im_est, cax<span class="op">=</span>cax1, label<span class="op">=</span><span class="st">&quot;dlight df/f&quot;</span>)</span>
<span id="cb13-44"><a href="#cb13-44" tabindex="-1"></a></span>
<span id="cb13-45"><a href="#cb13-45" tabindex="-1"></a>pos2 <span class="op">=</span> axes[<span class="dv">2</span>, <span class="dv">2</span>].get_position()</span>
<span id="cb13-46"><a href="#cb13-46" tabindex="-1"></a>cax2 <span class="op">=</span> fig.add_axes([pos2.x1 <span class="op">+</span> <span class="fl">0.015</span>, pos2.y0, <span class="fl">0.012</span>, pos2.height])</span>
<span id="cb13-47"><a href="#cb13-47" tabindex="-1"></a>fig.colorbar(im_alg, cax<span class="op">=</span>cax2, label<span class="op">=</span><span class="st">&quot;dlight df/f&quot;</span>)</span>
<span id="cb13-48"><a href="#cb13-48" tabindex="-1"></a></span>
<span id="cb13-49"><a href="#cb13-49" tabindex="-1"></a><span class="co"># Row labels on the left margin (matching original notebook)</span></span>
<span id="cb13-50"><a href="#cb13-50" tabindex="-1"></a><span class="cf">for</span> i, label <span class="kw">in</span> <span class="bu">enumerate</span>(row_titles):</span>
<span id="cb13-51"><a href="#cb13-51" tabindex="-1"></a>    fig.text(<span class="fl">0.02</span>, <span class="fl">0.80</span> <span class="op">-</span> i <span class="op">*</span> <span class="fl">0.14</span>, label,</span>
<span id="cb13-52"><a href="#cb13-52" tabindex="-1"></a>             ha<span class="op">=</span><span class="st">&quot;left&quot;</span>, va<span class="op">=</span><span class="st">&quot;center&quot;</span>, fontsize<span class="op">=</span><span class="dv">14</span>, rotation<span class="op">=</span><span class="dv">90</span>)</span>
<span id="cb13-53"><a href="#cb13-53" tabindex="-1"></a></span>
<span id="cb13-54"><a href="#cb13-54" tabindex="-1"></a>fig.subplots_adjust(hspace<span class="op">=</span><span class="fl">0.30</span>, wspace<span class="op">=</span><span class="fl">0.35</span>)</span>
<span id="cb13-55"><a href="#cb13-55" tabindex="-1"></a></span>
<span id="cb13-56"><a href="#cb13-56" tabindex="-1"></a>fig_path <span class="op">=</span> os.path.join(FIGURE_DIR, <span class="st">&quot;photometry_modeling_main.png&quot;</span>)</span>
<span id="cb13-57"><a href="#cb13-57" tabindex="-1"></a>fig.savefig(fig_path, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">&quot;tight&quot;</span>)</span>
<span id="cb13-58"><a href="#cb13-58" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Saved: </span><span class="sc">{</span>fig_path<span class="sc">}</span><span class="ss">&quot;</span>)</span>
<span id="cb13-59"><a href="#cb13-59" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="figs/photometry_modeling_main.png" /><!-- --></p>
<p>Each column corresponds to a developmental group (Early, Late,
Adult). The vertical dashed line marks motif onset. Warm colors indicate
higher dF/F (increased dopamine); cool colors indicate lower dF/F.</p>
<p><br />
</p>
</div>
<div id="template-convergence-across-developmental-stages"
class="section level2">
<h2>Template Convergence Across Developmental Stages</h2>
<p>To compare the <strong>shape</strong> of dopamine temporal patterns
across stages, templates are resampled onto a common normalized time
axis (0 = window start, 1 = window end). This removes differences in
sampling rate and window duration, isolating shape alone.</p>
<table>
<colgroup>
<col width="38%" />
<col width="61%" />
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Pearson r</strong></td>
<td>Linear shape similarity (+1 = identical, -1 = inverted)</td>
</tr>
<tr class="even">
<td><strong>RMSE</strong></td>
<td>Mean squared deviation in dF/F units</td>
</tr>
<tr class="odd">
<td><strong>Cosine similarity</strong></td>
<td>Amplitude-independent shape overlap (1 = perfect)</td>
</tr>
<tr class="even">
<td><strong>Peak position</strong></td>
<td>Location of template maximum on the 0-1 normalized axis</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb14"><pre
class="sourceCode python"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> pearsonr</span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a><span class="im">from</span> scipy.signal <span class="im">import</span> correlate</span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a><span class="kw">def</span> compare_templates(m_a, m_b, label_a<span class="op">=</span><span class="st">&quot;A&quot;</span>, label_b<span class="op">=</span><span class="st">&quot;B&quot;</span>):</span>
<span id="cb14-5"><a href="#cb14-5" tabindex="-1"></a>    <span class="co">&quot;&quot;&quot;Resample templates to a common axis and compute similarity metrics.&quot;&quot;&quot;</span></span>
<span id="cb14-6"><a href="#cb14-6" tabindex="-1"></a>    common_n <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb14-7"><a href="#cb14-7" tabindex="-1"></a>    ta <span class="op">=</span> np.interp(np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, common_n),</span>
<span id="cb14-8"><a href="#cb14-8" tabindex="-1"></a>                   np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="bu">len</span>(m_a)), m_a)</span>
<span id="cb14-9"><a href="#cb14-9" tabindex="-1"></a>    tb <span class="op">=</span> np.interp(np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, common_n),</span>
<span id="cb14-10"><a href="#cb14-10" tabindex="-1"></a>                   np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="bu">len</span>(m_b)), m_b)</span>
<span id="cb14-11"><a href="#cb14-11" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" tabindex="-1"></a>    r, pval   <span class="op">=</span> pearsonr(ta, tb)</span>
<span id="cb14-13"><a href="#cb14-13" tabindex="-1"></a>    rmse      <span class="op">=</span> np.sqrt(np.mean((ta <span class="op">-</span> tb) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb14-14"><a href="#cb14-14" tabindex="-1"></a>    cos_sim   <span class="op">=</span> np.dot(ta, tb) <span class="op">/</span> (np.linalg.norm(ta) <span class="op">*</span> np.linalg.norm(tb))</span>
<span id="cb14-15"><a href="#cb14-15" tabindex="-1"></a>    peak_a    <span class="op">=</span> np.argmax(ta) <span class="op">/</span> common_n</span>
<span id="cb14-16"><a href="#cb14-16" tabindex="-1"></a>    peak_b    <span class="op">=</span> np.argmax(tb) <span class="op">/</span> common_n</span>
<span id="cb14-17"><a href="#cb14-17" tabindex="-1"></a></span>
<span id="cb14-18"><a href="#cb14-18" tabindex="-1"></a>    <span class="co"># Cross-correlation lag (interior only, trim 10 % edges)</span></span>
<span id="cb14-19"><a href="#cb14-19" tabindex="-1"></a>    trim <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.1</span> <span class="op">*</span> common_n)</span>
<span id="cb14-20"><a href="#cb14-20" tabindex="-1"></a>    ta_i, tb_i <span class="op">=</span> ta[trim:<span class="op">-</span>trim], tb[trim:<span class="op">-</span>trim]</span>
<span id="cb14-21"><a href="#cb14-21" tabindex="-1"></a>    xcorr <span class="op">=</span> correlate(ta_i, tb_i, mode<span class="op">=</span><span class="st">&quot;full&quot;</span>)</span>
<span id="cb14-22"><a href="#cb14-22" tabindex="-1"></a>    lags  <span class="op">=</span> np.arange(<span class="op">-</span>(<span class="bu">len</span>(ta_i) <span class="op">-</span> <span class="dv">1</span>), <span class="bu">len</span>(ta_i)) <span class="op">/</span> common_n</span>
<span id="cb14-23"><a href="#cb14-23" tabindex="-1"></a>    xcorr_lag <span class="op">=</span> lags[np.argmax(xcorr)]</span>
<span id="cb14-24"><a href="#cb14-24" tabindex="-1"></a></span>
<span id="cb14-25"><a href="#cb14-25" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f&quot;</span><span class="ch">\n</span><span class="sc">{</span><span class="st">&#39;Comparison&#39;</span><span class="sc">:35s}</span><span class="ss">  Pearson r   p-value    RMSE   Cosine  &quot;</span></span>
<span id="cb14-26"><a href="#cb14-26" tabindex="-1"></a>          <span class="ss">f&quot;Peak_</span><span class="sc">{</span>label_a<span class="sc">}</span><span class="ss">  Peak_</span><span class="sc">{</span>label_b<span class="sc">}</span><span class="ss">  xcorr lag&quot;</span>)</span>
<span id="cb14-27"><a href="#cb14-27" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">&quot;-&quot;</span> <span class="op">*</span> <span class="dv">100</span>)</span>
<span id="cb14-28"><a href="#cb14-28" tabindex="-1"></a>    flag <span class="op">=</span> <span class="st">&quot; * interior peak at window boundary&quot;</span> <span class="cf">if</span> peak_a <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="kw">or</span> peak_a <span class="op">&gt;</span> <span class="fl">0.95</span> <span class="cf">else</span> <span class="st">&quot;&quot;</span></span>
<span id="cb14-29"><a href="#cb14-29" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f&quot;</span><span class="sc">{</span><span class="ss">f&#39;</span><span class="sc">{</span>label_b<span class="sc">}</span><span class="ss"> vs </span><span class="sc">{</span>label_a<span class="sc">}</span><span class="ss">&#39;</span><span class="sc">:35s}</span><span class="ss">  </span><span class="sc">{</span>r<span class="sc">:+.4f}</span><span class="ss">  </span><span class="sc">{</span>pval<span class="sc">:.2e}</span><span class="ss">  &quot;</span></span>
<span id="cb14-30"><a href="#cb14-30" tabindex="-1"></a>          <span class="ss">f&quot;</span><span class="sc">{</span>rmse<span class="sc">:.4f}</span><span class="ss">   </span><span class="sc">{</span>cos_sim<span class="sc">:+.3f}</span><span class="ss">   </span><span class="sc">{</span>peak_a<span class="sc">:.3f}</span><span class="ss">     </span><span class="sc">{</span>peak_b<span class="sc">:.3f}</span><span class="ss">   &quot;</span></span>
<span id="cb14-31"><a href="#cb14-31" tabindex="-1"></a>          <span class="ss">f&quot;</span><span class="sc">{</span>xcorr_lag<span class="sc">:+.3f}{</span>flag<span class="sc">}</span><span class="ss">&quot;</span>)</span>
<span id="cb14-32"><a href="#cb14-32" tabindex="-1"></a></span>
<span id="cb14-33"><a href="#cb14-33" tabindex="-1"></a>t_early <span class="op">=</span> early_dev_model.template[:, <span class="dv">0</span>]</span>
<span id="cb14-34"><a href="#cb14-34" tabindex="-1"></a>t_late  <span class="op">=</span> late_dev_model.template[:, <span class="dv">0</span>]</span>
<span id="cb14-35"><a href="#cb14-35" tabindex="-1"></a>t_adult <span class="op">=</span> adult_model.template[:, <span class="dv">0</span>]</span>
<span id="cb14-36"><a href="#cb14-36" tabindex="-1"></a></span>
<span id="cb14-37"><a href="#cb14-37" tabindex="-1"></a>compare_templates(t_early, t_late,  label_a<span class="op">=</span><span class="st">&quot;Early&quot;</span>, label_b<span class="op">=</span><span class="st">&quot;Late&quot;</span>)</span>
<span id="cb14-38"><a href="#cb14-38" tabindex="-1"></a>compare_templates(t_late,  t_adult, label_a<span class="op">=</span><span class="st">&quot;Late&quot;</span>,  label_b<span class="op">=</span><span class="st">&quot;Adult&quot;</span>)</span>
<span id="cb14-39"><a href="#cb14-39" tabindex="-1"></a>compare_templates(t_early, t_adult, label_a<span class="op">=</span><span class="st">&quot;Early&quot;</span>, label_b<span class="op">=</span><span class="st">&quot;Adult&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb15"><pre
class="sourceCode python"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>common_n <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a>norm_axis <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, common_n)</span>
<span id="cb15-3"><a href="#cb15-3" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" tabindex="-1"></a>t_early_n <span class="op">=</span> np.interp(norm_axis, np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="bu">len</span>(t_early)), t_early)</span>
<span id="cb15-5"><a href="#cb15-5" tabindex="-1"></a>t_late_n  <span class="op">=</span> np.interp(norm_axis, np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="bu">len</span>(t_late)),  t_late)</span>
<span id="cb15-6"><a href="#cb15-6" tabindex="-1"></a>t_adult_n <span class="op">=</span> np.interp(norm_axis, np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="bu">len</span>(t_adult)), t_adult)</span>
<span id="cb15-7"><a href="#cb15-7" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" tabindex="-1"></a>templates_norm <span class="op">=</span> {</span>
<span id="cb15-9"><a href="#cb15-9" tabindex="-1"></a>    <span class="st">&quot;Early Dev&quot;</span>: t_early_n,</span>
<span id="cb15-10"><a href="#cb15-10" tabindex="-1"></a>    <span class="st">&quot;Late Dev&quot;</span>: t_late_n,</span>
<span id="cb15-11"><a href="#cb15-11" tabindex="-1"></a>    <span class="st">&quot;Adult&quot;</span>: t_adult_n,</span>
<span id="cb15-12"><a href="#cb15-12" tabindex="-1"></a>}</span>
<span id="cb15-13"><a href="#cb15-13" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" tabindex="-1"></a>C_ADULT <span class="op">=</span> <span class="st">&quot;#1f77b4&quot;</span></span>
<span id="cb15-15"><a href="#cb15-15" tabindex="-1"></a>C_LATE  <span class="op">=</span> <span class="st">&quot;#90CAF9&quot;</span></span>
<span id="cb15-16"><a href="#cb15-16" tabindex="-1"></a>C_EARLY <span class="op">=</span> <span class="st">&quot;#90CAF9&quot;</span></span>
<span id="cb15-17"><a href="#cb15-17" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" tabindex="-1"></a>TICK_LOCS   <span class="op">=</span> [<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="dv">1</span>]</span>
<span id="cb15-19"><a href="#cb15-19" tabindex="-1"></a>TICK_LABELS <span class="op">=</span> [<span class="st">&quot;0&quot;</span>, <span class="st">&quot;0.5&quot;</span>, <span class="st">&quot;1&quot;</span>]</span>
<span id="cb15-20"><a href="#cb15-20" tabindex="-1"></a>X_LABEL     <span class="op">=</span> <span class="st">&quot;Normalized time&quot;</span></span>
<span id="cb15-21"><a href="#cb15-21" tabindex="-1"></a>Y_LABEL     <span class="op">=</span> <span class="st">&quot;Model Template (dF/F)&quot;</span></span>
<span id="cb15-22"><a href="#cb15-22" tabindex="-1"></a></span>
<span id="cb15-23"><a href="#cb15-23" tabindex="-1"></a>fig_conv, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.2</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-24"><a href="#cb15-24" tabindex="-1"></a></span>
<span id="cb15-25"><a href="#cb15-25" tabindex="-1"></a><span class="co"># ── Left panel: Late Dev vs Adult ────────────────────────────────────────────</span></span>
<span id="cb15-26"><a href="#cb15-26" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">0</span>]</span>
<span id="cb15-27"><a href="#cb15-27" tabindex="-1"></a>ax.plot(norm_axis, templates_norm[<span class="st">&quot;Adult&quot;</span>],</span>
<span id="cb15-28"><a href="#cb15-28" tabindex="-1"></a>        color<span class="op">=</span>C_ADULT, ls<span class="op">=</span><span class="st">&quot;-&quot;</span>, lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="st">&quot;Adult&quot;</span>)</span>
<span id="cb15-29"><a href="#cb15-29" tabindex="-1"></a>ax.plot(norm_axis, templates_norm[<span class="st">&quot;Late Dev&quot;</span>],</span>
<span id="cb15-30"><a href="#cb15-30" tabindex="-1"></a>        color<span class="op">=</span>C_LATE,  ls<span class="op">=</span><span class="st">&quot;-&quot;</span>, lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="st">&quot;Late Dev&quot;</span>)</span>
<span id="cb15-31"><a href="#cb15-31" tabindex="-1"></a>norm_onset_juv <span class="op">=</span> JUV_MOTIF_ONSET <span class="op">/</span> JUV_TOTAL_WINDOW</span>
<span id="cb15-32"><a href="#cb15-32" tabindex="-1"></a>norm_onset_adult <span class="op">=</span> ADULT_MOTIF_ONSET <span class="op">/</span> ADULT_TOTAL_WINDOW</span>
<span id="cb15-33"><a href="#cb15-33" tabindex="-1"></a>ax.axvline(norm_onset_juv, color<span class="op">=</span>C_LATE, linestyle<span class="op">=</span><span class="st">&quot;:&quot;</span>, lw<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb15-34"><a href="#cb15-34" tabindex="-1"></a>ax.axvline(norm_onset_adult, color<span class="op">=</span>C_ADULT, linestyle<span class="op">=</span><span class="st">&quot;:&quot;</span>, lw<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb15-35"><a href="#cb15-35" tabindex="-1"></a>ax.set_title(<span class="st">&quot;Late Dev vs Adult&quot;</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb15-36"><a href="#cb15-36" tabindex="-1"></a>ax.set_xlabel(X_LABEL, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb15-37"><a href="#cb15-37" tabindex="-1"></a>ax.set_ylabel(Y_LABEL, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb15-38"><a href="#cb15-38" tabindex="-1"></a>ax.set_xticks(TICK_LOCS)</span>
<span id="cb15-39"><a href="#cb15-39" tabindex="-1"></a>ax.set_xticklabels(TICK_LABELS)</span>
<span id="cb15-40"><a href="#cb15-40" tabindex="-1"></a>ax.set_yticks([<span class="op">-</span><span class="fl">0.5</span>, <span class="dv">0</span>, <span class="fl">0.5</span>, <span class="fl">1.0</span>])</span>
<span id="cb15-41"><a href="#cb15-41" tabindex="-1"></a>ax.legend(fontsize<span class="op">=</span><span class="dv">12</span>, loc<span class="op">=</span><span class="st">&quot;upper right&quot;</span>)</span>
<span id="cb15-42"><a href="#cb15-42" tabindex="-1"></a>ax.spines[[<span class="st">&quot;top&quot;</span>, <span class="st">&quot;right&quot;</span>]].set_visible(<span class="va">False</span>)</span>
<span id="cb15-43"><a href="#cb15-43" tabindex="-1"></a>ax.set_ylim(<span class="op">-</span><span class="fl">0.6</span>, <span class="fl">1.0</span>)</span>
<span id="cb15-44"><a href="#cb15-44" tabindex="-1"></a></span>
<span id="cb15-45"><a href="#cb15-45" tabindex="-1"></a><span class="co"># ── Right panel: Late Dev vs Early Dev ───────────────────────────────────────</span></span>
<span id="cb15-46"><a href="#cb15-46" tabindex="-1"></a>ax2 <span class="op">=</span> axes[<span class="dv">1</span>]</span>
<span id="cb15-47"><a href="#cb15-47" tabindex="-1"></a>ax2.plot(norm_axis, templates_norm[<span class="st">&quot;Late Dev&quot;</span>],</span>
<span id="cb15-48"><a href="#cb15-48" tabindex="-1"></a>         color<span class="op">=</span>C_LATE,  ls<span class="op">=</span><span class="st">&quot;-&quot;</span>,  lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="st">&quot;Late Dev&quot;</span>)</span>
<span id="cb15-49"><a href="#cb15-49" tabindex="-1"></a>ax2.plot(norm_axis, templates_norm[<span class="st">&quot;Early Dev&quot;</span>],</span>
<span id="cb15-50"><a href="#cb15-50" tabindex="-1"></a>         color<span class="op">=</span>C_EARLY, ls<span class="op">=</span><span class="st">&quot;--&quot;</span>, lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="st">&quot;Early Dev&quot;</span>)</span>
<span id="cb15-51"><a href="#cb15-51" tabindex="-1"></a>norm_onset_juv <span class="op">=</span> JUV_MOTIF_ONSET <span class="op">/</span> JUV_TOTAL_WINDOW</span>
<span id="cb15-52"><a href="#cb15-52" tabindex="-1"></a>ax2.axvline(norm_onset_juv, color<span class="op">=</span><span class="st">&quot;gray&quot;</span>, linestyle<span class="op">=</span><span class="st">&quot;:&quot;</span>, lw<span class="op">=</span><span class="fl">1.5</span>, label<span class="op">=</span><span class="st">&quot;Motif Onset&quot;</span>)</span>
<span id="cb15-53"><a href="#cb15-53" tabindex="-1"></a>ax2.set_title(<span class="st">&quot;Late Dev vs Early Dev&quot;</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb15-54"><a href="#cb15-54" tabindex="-1"></a>ax2.set_xlabel(X_LABEL, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb15-55"><a href="#cb15-55" tabindex="-1"></a>ax2.set_xticks(TICK_LOCS)</span>
<span id="cb15-56"><a href="#cb15-56" tabindex="-1"></a>ax2.set_xticklabels(TICK_LABELS)</span>
<span id="cb15-57"><a href="#cb15-57" tabindex="-1"></a>ax2.legend(fontsize<span class="op">=</span><span class="dv">11</span>, loc<span class="op">=</span><span class="st">&quot;upper right&quot;</span>)</span>
<span id="cb15-58"><a href="#cb15-58" tabindex="-1"></a>ax2.spines[[<span class="st">&quot;top&quot;</span>, <span class="st">&quot;right&quot;</span>]].set_visible(<span class="va">False</span>)</span>
<span id="cb15-59"><a href="#cb15-59" tabindex="-1"></a></span>
<span id="cb15-60"><a href="#cb15-60" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb15-61"><a href="#cb15-61" tabindex="-1"></a>fig_path <span class="op">=</span> os.path.join(FIGURE_DIR, <span class="st">&quot;photometry_modeling_templates.png&quot;</span>)</span>
<span id="cb15-62"><a href="#cb15-62" tabindex="-1"></a>fig_conv.savefig(fig_path, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">&quot;tight&quot;</span>)</span>
<span id="cb15-63"><a href="#cb15-63" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f&quot;Saved: </span><span class="sc">{</span>fig_path<span class="sc">}</span><span class="ss">&quot;</span>)</span>
<span id="cb15-64"><a href="#cb15-64" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="figs/photometry_modeling_templates.png" /><!-- --></p>
<p>Overlaid consensus templates on a common normalized time axis.
Divergence between curves reflects developmental changes in the typical
dopamine temporal profile.</p>
<p><br />
</p>
</div>
<div id="summary" class="section level2">
<h2>Summary</h2>
<p>This vignette demonstrated:</p>
<ol style="list-style-type: decimal">
<li><strong>Data pooling</strong> - Aggregating dLight recordings across
animals at matched developmental stages (early juvenile, late juvenile,
and full adult).</li>
<li><strong>Shift-only time warping</strong> - Fitting unsupervised
<code>ShiftWarping</code> models (via <code>affinewarp</code>) to each
group using <code>maxlag=0.2</code> and
<code>smoothness_reg_scale=10.0</code>, recovering per-trial shifts and
consensus templates over 20 iterations.</li>
<li><strong>Model diagnostics</strong> - Inspecting learning curves to
confirm convergence.</li>
<li><strong>Template comparison</strong> - Quantifying shape similarity
across developmental stages using Pearson correlation, RMSE, and cosine
similarity on a normalized time axis.</li>
</ol>
<p>Together, these analyses reveal how the <strong>temporal structure of
dopamine activity</strong> evolves across vocal development,
complementing the supervised alignment results from the
individual-animal analyses.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
