# .github/workflows/render-site.yml

on:
  push:
    branches:
      - main

name: Render and Deploy RMarkdown Website

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1' 

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::rmarkdown
            any::knitr
            # Add any other R packages the site needs here
            # For example: any::dplyr, any::ggplot2

      - name: Render RMarkdown Website
        run: Rscript -e 'rmarkdown::render_site()'

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          # The directory where your website is built
          build_dir: docs
          # The API token is created automatically by the workflow
          token: ${{ secrets.GITHUB_TOKEN }}